name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test-and-clippy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install libuv-dev
        run: sudo apt update && sudo apt install -y libuv1-dev

      - name: Run tests
        run: cargo test --verbose

      - name: Run clippy
        run: cargo clippy
